name: auth-test

on:
  push:
    branches: [ main ]
    path:
      - 'auth/**'
  pull_request:
    branches: [ main ]
    path:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm install && npm run test:ci
