name: payment-test

on:
  push:
    branches: [ main ]
    path:
      - 'payment/**'
  pull_request:
    branches: [ main ]
    path:
      - 'payment/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd payment && npm install && npm run test:ci
